variable "aws_region" {}
variable "vpc_cidr" {}
variable "vpc_id" {}
variable "subnet_cidr" {}
variable "subnet_id" {}
variable "vpc_tag" {}
variable "subnet_tag" {}
variable "sg_tag" {}
variable "sg_name" {}
